services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Admin1234
      POSTGRES_DB: real_estate
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Mount SQL script
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery_worker:
    build: ./app
    container_name: celery_worker
    depends_on:
      - redis
      - postgres
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      API_KEY: sk-1c976bc892554124a23dd746ce79720a
      PYTHONPATH: /app
    # Make sure the app module is correctly specified
    command: celery -A celery_app worker --loglevel=info --concurrency=4
    volumes:
      - ./app:/app # Make sure your app code is mounted
  

volumes:
  postgres_data:
  redis_data:
