SCRAPER_SOURCES = {
    "sreality": {
        "country":"CZ",
        "currency": "CZK",
        "base_url": "https://www.sreality.cz/hledani",
        "rent_flat": "/pronajem/byty",
        "rent_house": "/pronajem/domy",
        "sale_flat": "/prodej/byty",
        "sale_house": "/prodej/domy",
    },
    "reas": {
        "country":"CZ",
        "currency": "CZK",
        "base_url": "https://www.reas.cz",
        "sale_flat": "/prodej/byty",
        "sale_house": "/prodej/domy",
    },
    "bezrealitky": {
        "country":"CZ",
        "currency": "CZK",
        "base_url": "https://www.bezrealitky.cz/vypis",
        "rent_flat": "/nabidka-pronajem/byt/ceska-republika",
        "rent_house": "/nabidka-pronajem/dum/ceska-republika",
        "sale_flat": "/nabidka-prodej/byt/ceska-republika",
        "sale_house": "/nabidka-prodej/dum/ceska-republika",
    },
    "ceske_reality": {
        "country":"CZ",
        "currency": "CZK",
        "base_url": "https://www.ceskereality.cz",
        "rent_flat": "/pronajem/byty/",
        "rent_house": "/pronajem/rodinne-domy/",
        "sale_flat": "/prodej/byty/",
        "sale_house": "/prodej/rodinne-domy/",
    },
    "idnes": {
        "country":"CZ",
        "currency": "CZK",
        "base_url": "https://reality.idnes.cz/s",
        "rent_flat": "/pronajem/byty/",
        "rent_house": "/pronajem/domy/",
        "sale_flat": "/prodej/byty/",
        "sale_house": "/prodej/domy/",
    },
}
